# pyright: reportArgumentType=false, reportUnknownVariableType=false, reportUnknownMemberType=false
import os
import sqlite3
from typing import Any, Iterable

import psycopg

SQLITE_DEFAULT_PATH = os.path.join("data", "stock_system.db")

TABLE_ORDER = [
    "users",
    "user_watchlist",
    "user_settings",
    "indicator_adjustment_log",
    "market_raw",
    "market_scores",
    "stock_raw",
    "stock_scores",
    "stock_score_cache_15d",
]

CONFLICT_KEYS = {
    "users": ["id"],
    "user_watchlist": ["id"],
    "user_settings": ["id"],
    "indicator_adjustment_log": ["id"],
    "market_raw": ["date"],
    "market_scores": ["date"],
    "stock_raw": ["date", "symbol", "timeframe"],
    "stock_scores": ["date", "symbol", "timeframe"],
    "stock_score_cache_15d": ["cache_day", "symbol", "timeframe", "trade_date"],
}


def q(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sqlite_table_exists(conn: sqlite3.Connection, table: str) -> bool:
    cur = conn.cursor()
    cur.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?", (table,))
    return cur.fetchone() is not None


def sqlite_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    cur = conn.cursor()
    cur.execute(f"PRAGMA table_info({table})")
    return [row[1] for row in cur.fetchall()]


def fetch_sqlite_rows(conn: sqlite3.Connection, table: str, columns: Iterable[str]) -> list[tuple[Any, ...]]:
    cols_sql = ", ".join(q(c) for c in columns)
    cur = conn.cursor()
    cur.execute(f"SELECT {cols_sql} FROM {q(table)}")
    return cur.fetchall()


def ensure_postgres_schema(pg: psycopg.Connection) -> None:
    cur = pg.cursor()
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            username_lower TEXT,
            last_login_at TEXT
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS user_watchlist (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            symbol TEXT NOT NULL,
            sort_order INTEGER,
            added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, symbol),
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS user_settings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            setting_key TEXT NOT NULL,
            setting_value TEXT,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, setting_key),
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS indicator_adjustment_log (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            symbol TEXT NOT NULL,
            indicator_type TEXT NOT NULL,
            timeframe TEXT,
            change_pct REAL,
            original_score INTEGER,
            adjusted_score INTEGER,
            adjusted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS market_raw (
            date TEXT PRIMARY KEY,
            taiex_price REAL,
            twd_fx REAL,
            foreign_buy REAL,
            sitc_buy REAL,
            dealer_buy REAL,
            is_ready INTEGER DEFAULT 0
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS market_scores (
            date TEXT PRIMARY KEY,
            score_a INTEGER,
            score_b_tx INTEGER,
            score_b_mtx INTEGER,
            score_b_elec INTEGER,
            score_b_fin INTEGER,
            score_c_total INTEGER,
            diagnosis TEXT,
            FOREIGN KEY(date) REFERENCES market_raw(date)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS stock_raw (
            date TEXT,
            symbol TEXT,
            timeframe TEXT,
            open REAL,
            high REAL,
            low REAL,
            close REAL,
            volume INTEGER,
            PRIMARY KEY (date, symbol, timeframe)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS stock_scores (
            date TEXT,
            symbol TEXT,
            timeframe TEXT,
            ma_score INTEGER,
            kd_score INTEGER,
            rsi_score INTEGER,
            macd_score INTEGER,
            vol_score INTEGER,
            total_score INTEGER,
            kd_entangled INTEGER,
            rsi_entangled INTEGER,
            macd_entangled INTEGER,
            PRIMARY KEY (date, symbol, timeframe)
        )
        '''
    )
    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS stock_score_cache_15d (
            cache_day TEXT,
            symbol TEXT,
            timeframe TEXT,
            trade_date TEXT,
            total_score INTEGER,
            ma_score INTEGER,
            kd_score INTEGER,
            rsi_score INTEGER,
            macd_score INTEGER,
            vol_score INTEGER,
            bias_pct REAL,
            close_price REAL,
            macd_osc REAL,
            macd_prev_osc REAL,
            kd_k REAL,
            kd_prev_k REAL,
            kd_d REAL,
            kd_prev_d REAL,
            kd_change_pct REAL,
            PRIMARY KEY (cache_day, symbol, timeframe, trade_date)
        )
        '''
    )
    cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users(username_lower)")
    pg.commit()


def build_upsert_sql(table: str, columns: list[str]) -> str:
    cols_sql = ", ".join(q(c) for c in columns)
    placeholders = ", ".join(["%s"] * len(columns))
    conflict_cols = CONFLICT_KEYS[table]
    conflict_sql = ", ".join(q(c) for c in conflict_cols)
    update_cols = [c for c in columns if c not in conflict_cols]

    if update_cols:
        update_sql = ", ".join(f"{q(c)} = EXCLUDED.{q(c)}" for c in update_cols)
        return (
            f"INSERT INTO {q(table)} ({cols_sql}) VALUES ({placeholders}) "
            f"ON CONFLICT ({conflict_sql}) DO UPDATE SET {update_sql}"
        )

    return f"INSERT INTO {q(table)} ({cols_sql}) VALUES ({placeholders}) ON CONFLICT ({conflict_sql}) DO NOTHING"


def postgres_count(pg: psycopg.Connection, table: str) -> int:
    cur = pg.cursor()
    cur.execute(f"SELECT COUNT(*) FROM {q(table)}")
    row = cur.fetchone()
    return int(row[0] if row else 0)


def reset_identity_sequences(pg: psycopg.Connection) -> None:
    cur = pg.cursor()
    for table in ("users", "user_watchlist", "user_settings", "indicator_adjustment_log"):
        cur.execute(
            f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), COALESCE((SELECT MAX(id) FROM {table}), 1), true)"
        )
    pg.commit()


def main() -> int:
    database_url = os.environ.get("DATABASE_URL", "").strip()
    sqlite_path = os.environ.get("STOCK_DB_PATH", SQLITE_DEFAULT_PATH)

    if not database_url:
        print("ERROR: DATABASE_URL is empty. Please set Postgres connection string first.")
        return 2

    if database_url.startswith("postgres://"):
        database_url = "postgresql://" + database_url[len("postgres://"):]

    if not os.path.exists(sqlite_path):
        print(f"ERROR: SQLite file not found: {sqlite_path}")
        return 2

    print(f"Using SQLite: {sqlite_path}")
    print("Connecting Postgres...")

    sqlite_conn = sqlite3.connect(sqlite_path)
    pg_conn = psycopg.connect(database_url)

    try:
        ensure_postgres_schema(pg_conn)
        migrated_counts: dict[str, int] = {}

        for table in TABLE_ORDER:
            if not sqlite_table_exists(sqlite_conn, table):
                print(f"SKIP {table}: table missing in SQLite")
                continue

            cols = sqlite_columns(sqlite_conn, table)
            rows = fetch_sqlite_rows(sqlite_conn, table, cols)
            if not rows:
                print(f"SKIP {table}: 0 rows")
                migrated_counts[table] = 0
                continue

            sql = build_upsert_sql(table, cols)
            cur = pg_conn.cursor()
            cur.executemany(sql, rows)
            pg_conn.commit()
            migrated_counts[table] = len(rows)
            print(f"OK {table}: migrated {len(rows)} rows")

        reset_identity_sequences(pg_conn)

        print("\nValidation counts (Postgres):")
        for table in TABLE_ORDER:
            try:
                n = postgres_count(pg_conn, table)
                print(f"- {table}: {n}")
            except Exception:
                print(f"- {table}: (missing)")

        print("\nMigration finished.")
        return 0
    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
